const productos = [
  // --- BELLEZA ---
  { id: "BELL01", nombre: "SECADOR DE PELO ZAFIRE", precio: 99, precioAnterior: 0, cat: "BELLEZA", foto: "fotos/BELLEZA/4.webp", oferta: false, stock: true },
  { id: "BELL02", nombre: "PLANCHITA DE PELO PROFESIONAL", precio: 99, precioAnterior: 0, cat: "BELLEZA", foto: "fotos/BELLEZA/3.webp", oferta: false, stock: true },
  { id: "BELL03", nombre: "CEPILLO ALISADOR", precio: 99, precioAnterior: 0, cat: "BELLEZA", foto: "fotos/BELLEZA/cepillo.webp", oferta: false, stock: true },
  { id: "BELL05", nombre: "AFEITADORA", precio: 99, precioAnterior: 0, cat: "BELLEZA", foto: "fotos/BELLEZA/1.webp", oferta: false, stock: true },
  { id: "BELL06", nombre: "AFEITADORA", precio: 99, precioAnterior: 0, cat: "BELLEZA", foto: "fotos/BELLEZA/2.webp", oferta: false, stock: true },

  // --- HOGAR ---
  { id: "HOG01", nombre: "FREIDORA DE AIRE DIGITAL", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/1.webp", oferta: false, stock: true },
  { id: "HOG02", nombre: "HORNO ELÉCTRICO GRILL", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/2.webp", oferta: false, stock: true },
  { id: "HOG03", nombre: "CAFETERA EXPRESSO PROFESIONAL", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/3.webp", oferta: false, stock: true },
  { id: "HOG04", nombre: "SACA CORCHOS", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/4.webp", oferta: false, stock: true },
  { id: "HOG05", nombre: "SET DE VINO / ABREBOTELLAS", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/5.webp", oferta: false, stock: true },
  { id: "HOG06", nombre: "SET SOMMELIER MADERA", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/6.webp", oferta: false, stock: true },
  { id: "HOG07", nombre: "SET ACCESORIOS VINO PROFESIONAL", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/7.webp", oferta: false, stock: true },
  { id: "HOG10", nombre: "CAFETERA DE FILTRO", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/10.webp", oferta: false, stock: true },
  { id: "HOG11", nombre: "CAFETERA DE FILTRO", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/11.webp", oferta: false, stock: true },
  { id: "HOG12", nombre: "CAFETERA DE FILTRO", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/12.webp", oferta: false, stock: true },
  { id: "HOG13", nombre: "CAFETERA PRENSA FRANCESA", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/13.webp", oferta: false, stock: true },
  { id: "HOG14", nombre: "BALANZA DE PRECISIÓN DIGITAL", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/14.webp", oferta: false, stock: true },
  { id: "HOG15", nombre: "BALANZA DE COCINA BLANCA", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/20.webp", oferta: false, stock: true },
  { id: "HOG16", nombre: "BALANZA BAÑO DISEÑO FRUTAS", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/16.webp", oferta: false, stock: true },
  { id: "HOG17", nombre: "SANDWICHERA ELÉCTRICA DOBLE", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/17.webp", oferta: false, stock: true },
  { id: "HOG18", nombre: "BALANZA COCINA ACERO INOX", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/18.webp", oferta: false, stock: true },
  { id: "HOG19", nombre: "MINI BALANZA JOYERA", precio: 99, precioAnterior: 0, cat: "HOGAR", foto: "fotos/HOGAR/19.webp", oferta: false, stock: true },

  // --- DECO ---
  { id: "DEC01", nombre: "LÁMPARA ATARDECER", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/1.webp", oferta: false, stock: true },
  { id: "DEC02", nombre: "HUMIFICADOR LLAMA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/2.webp", oferta: false, stock: true },
  { id: "DEC03", nombre: "HUMIFICADOR HONGO", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/3.webp", oferta: false, stock: true },
  { id: "DEC04", nombre: "VELADOR GATITO FLEXIBLE", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/4.webp", oferta: false, stock: true },
  { id: "DEC05", nombre: "VELADOR ASTRONAUTA LUNA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/5.webp", oferta: false, stock: true },
  { id: "DEC06", nombre: "LÁMPARA DE MESA NÓRDICA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/6.webp", oferta: false, stock: true },
  { id: "DEC07", nombre: "PROYECTOR ASTRONAUTA GALAXIA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/7.webp", oferta: false, stock: true },
  { id: "DEC08", nombre: "VELADOR LED MINIMALISTA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/8.webp", oferta: false, stock: true },
  { id: "DEC09", nombre: "HUMIDIFICADOR LÁMPARA MADERA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/9.webp", oferta: false, stock: true },
  { id: "DEC10", nombre: "VELADOR LED ESCRITORIO", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/10.webp", oferta: false, stock: true },
  { id: "DEC11", nombre: "VELADOR CANGREJO INFANTIL", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/11.webp", oferta: false, stock: true },
  { id: "DEC12", nombre: "VELADOR CARACOL INFANTIL", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/12.webp", oferta: false, stock: true },
  { id: "DEC13", nombre: "LÁMPARA DE PARED MODERNA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/13.webp", oferta: false, stock: true },
  { id: "DEC14", nombre: "VELADOR CARPINCHO / CAPYBARA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/14.webp", oferta: false, stock: true },
  { id: "DEC15", nombre: "LÁMPARA ESCRITORIO INALÁMBRICA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/15.webp", oferta: false, stock: true },
  { id: "DEC16", nombre: "PROYECTOR PARLANTE ASTRONAUTA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/16.webp", oferta: false, stock: true },
  { id: "DEC17", nombre: "PROYECTOR ESTRELLAS GIRATORIO", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/17.webp", oferta: false, stock: true },
  { id: "DEC18", nombre: "VELADOR CARACOL DOBLE", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/18.webp", oferta: false, stock: true },
  { id: "DEC19", nombre: "LÁMPARA DE MESA LUNA", precio: 99, precioAnterior: 0, cat: "DECO", foto: "fotos/DECO/19.webp", oferta: false, stock: true },

  // --- PARLANTES ---
  { id: "PAR01", nombre: "PARLANTE PORTÁTIL BT", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/1.webp", oferta: false, stock: true },
  { id: "PAR02", nombre: "PARLANTE BT 2", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/2.webp", oferta: false, stock: true },
  { id: "PAR03", nombre: "PARLANTE BT 3", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/3.webp", oferta: false, stock: true },
  { id: "PAR04", nombre: "PARLANTE BT 4", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/4.webp", oferta: false, stock: true },
  { id: "PAR05", nombre: "PARLANTE BT 5", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/5.webp", oferta: false, stock: true },
  { id: "PAR06", nombre: "PARLANTE BT 6", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/6.webp", oferta: false, stock: true },
  { id: "PAR07", nombre: "PARLANTE BT 7", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/7.webp", oferta: false, stock: true },
  { id: "PAR08", nombre: "PARLANTE BT 8", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/8.webp", oferta: false, stock: true },
  { id: "PAR09", nombre: "PARLANTE BT 9", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/9.webp", oferta: false, stock: true },
  { id: "PAR10", nombre: "PARLANTE BT 10", precio: 99, precioAnterior: 0, cat: "PARLANTES", foto: "fotos/PARLANTES/10.webp", oferta: false, stock: true },

  // --- MICRÓFONOS ---
  { id: "MIC01", nombre: "MICRÓFONO PROFESIONAL", precio: 99, precioAnterior: 0, cat: "MICRÓFONOS", foto: "fotos/MICROFONOS/1.webp", oferta: false, stock: true },
  { id: "MIC02", nombre: "MICRÓFONO 2", precio: 99, precioAnterior: 0, cat: "MICRÓFONOS", foto: "fotos/MICROFONOS/2.webp", oferta: false, stock: true },
  { id: "MIC03", nombre: "MICRÓFONO 3", precio: 99, precioAnterior: 0, cat: "MICRÓFONOS", foto: "fotos/MICROFONOS/3.webp", oferta: false, stock: true },
  { id: "MIC04", nombre: "MICRÓFONO 4", precio: 99, precioAnterior: 0, cat: "MICRÓFONOS", foto: "fotos/MICROFONOS/4.webp", oferta: false, stock: true },
  { id: "MIC05", nombre: "MICRÓFONO 5", precio: 99, precioAnterior: 0, cat: "MICRÓFONOS", foto: "fotos/MICROFONOS/5.webp", oferta: false, stock: true },
  { id: "MIC06", nombre: "MICRÓFONO 6", precio: 99, precioAnterior: 0, cat: "MICRÓFONOS", foto: "fotos/MICROFONOS/6.webp", oferta: false, stock: true },
  { id: "MIC07", nombre: "MICRÓFONO 7", precio: 99, precioAnterior: 0, cat: "MICRÓFONOS", foto: "fotos/MICROFONOS/7.webp", oferta: false, stock: true },

  // --- AURICULARES ---
  { id: "AUR01", nombre: "AURICULAR VINCHA", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/1.webp", oferta: false, stock: true },
  { id: "AUR02", nombre: "AURICULAR 2", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/2.webp", oferta: false, stock: true },
  { id: "AUR03", nombre: "AURICULAR 3", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/3.webp", oferta: false, stock: true },
  { id: "AUR04", nombre: "AURICULAR INFANTIL", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/4.webp", oferta: false, stock: true },
  { id: "AUR05", nombre: "AURICULAR 5", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/5.webp", oferta: false, stock: true },
  { id: "AUR06", nombre: "AURICULAR 6", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/6.webp", oferta: false, stock: true },
  { id: "AUR07", nombre: "AURICULAR 7", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/7.webp", oferta: false, stock: true },
  { id: "AUR08", nombre: "AURICULARES BT", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/8.webp", oferta: false, stock: true },
  { id: "AUR09", nombre: "AURICULARES 9", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/9.webp", oferta: false, stock: true },
  { id: "AUR10", nombre: "AURICULARES 10", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/10.webp", oferta: false, stock: true },
  { id: "AUR11", nombre: "AURICULARES TWS", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/11.webp", oferta: false, stock: true },
  { id: "AUR12", nombre: "AURICULARES 12", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/12.webp", oferta: false, stock: true },
  { id: "AUR13", nombre: "AURICULARES 13", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/13.webp", oferta: false, stock: true },
  { id: "AUR14", nombre: "AURICULARES 14", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/14.webp", oferta: false, stock: true },
  { id: "AUR15", nombre: "AURICULARES 15", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/15.webp", oferta: false, stock: true },
  { id: "AUR16", nombre: "AURICULARES 16", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/16.webp", oferta: false, stock: true },
  { id: "AUR17", nombre: "AURICULARES 17", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/17.webp", oferta: false, stock: true },
  { id: "AUR18", nombre: "AURICULARES", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/18.webp", oferta: false, stock: true },
  { id: "AUR19", nombre: "AURICULARES", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/19.webp", oferta: false, stock: true },
  { id: "AUR21", nombre: "AURICULARES", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/20.webp", oferta: false, stock: true },
  { id: "AUR22", nombre: "AURICULARES", precio: 99, precioAnterior: 0, cat: "AURICULARES", foto: "fotos/AURICULARES/21.webp", oferta: false, stock: true },

  // --- INFORMÁTICA ---
  { id: "INF01", nombre: "TV BOX 4K", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/1.webp", oferta: false, stock: true },
  { id: "INF02", nombre: "TV BOX", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/2.webp", oferta: false, stock: true },
  { id: "INF03", nombre: "MOUSE GAMER", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/3.webp", oferta: false, stock: true },
  { id: "INF04", nombre: "MOUSE ÓPTICO", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/4.webp", oferta: false, stock: true },
  { id: "INF05", nombre: "MOUSE PAD LED", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/5.webp", oferta: false, stock: true },
  { id: "INF06", nombre: "TECLADO MECÁNICO", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/6.webp", oferta: false, stock: true },
  { id: "INF07", nombre: "COMBO TECLADO Y MOUSE", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/7.webp", oferta: false, stock: true },
  { id: "INF08", nombre: "JOYSTICK PC/PS3", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/8.webp", oferta: false, stock: true },
  { id: "INF09", nombre: "TECLADO INALÁMBRICO", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/9.webp", oferta: false, stock: true },
  { id: "INF14", nombre: "MOUSE INALÁMBRICO", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/14.webp", oferta: false, stock: true },
  { id: "INF15", nombre: "MOUSE 15", precio: 99, precioAnterior: 0, cat: "INFORMÁTICA", foto: "fotos/INFORMATICA/15.webp", oferta: false, stock: true },

  // --- JUGUETES ---
  { id: "JUG01", nombre: "CÁMARA DIGITAL INFANTIL", precio: 99, precioAnterior: 0, cat: "JUGUETES", foto: "fotos/JUGUETES/1.webp", oferta: false, stock: true },
  { id: "JUG02", nombre: "CAMIÓN DE CONSTRUCCIÓN", precio: 99, precioAnterior: 0, cat: "JUGUETES", foto: "fotos/JUGUETES/2.webp", oferta: false, stock: true },
  { id: "JUG03", nombre: "PISTOLA LANZA DARDOS", precio: 99, precioAnterior: 0, cat: "JUGUETES", foto: "fotos/JUGUETES/3.webp", oferta: false, stock: true },
  { id: "JUG04", nombre: "AMETRALLADORA DORADA", precio: 99, precioAnterior: 0, cat: "JUGUETES", foto: "fotos/JUGUETES/4.webp", oferta: false, stock: true },
  { id: "JUG05", nombre: "SET LANZA DARDOS ACCESORIOS", precio: 99, precioAnterior: 0, cat: "JUGUETES", foto: "fotos/JUGUETES/5.webp", oferta: false, stock: true },
  { id: "JUG06", nombre: "PISTOLA AUTOMÁTICA", precio: 99, precioAnterior: 0, cat: "JUGUETES", foto: "fotos/JUGUETES/6.webp", oferta: false, stock: true },

  // --- LIBRERÍA ---
  { id: "LIB01", nombre: "SET RESALTADORES FRAGANCIA", precio: 99, precioAnterior: 0, cat: "LIBRERÍA", foto: "fotos/LIBRERIA/1.webp", oferta: false, stock: true },
  { id: "LIB02", nombre: "MOCHILA INFANTIL DINO", precio: 99, precioAnterior: 0, cat: "LIBRERÍA", foto: "fotos/LIBRERIA/2.webp", oferta: false, stock: true },
  { id: "LIB03", nombre: "MOCHILA INFANTIL LECHUZA", precio: 99, precioAnterior: 0, cat: "LIBRERÍA", foto: "fotos/LIBRERIA/3.webp", oferta: false, stock: true },
  { id: "LIB04", nombre: "MOCHILA ESCOLAR ESPACIAL", precio: 99, precioAnterior: 0, cat: "LIBRERÍA", foto: "fotos/LIBRERIA/4.webp", oferta: false, stock: true },
  { id: "LIB05", nombre: "SET LAPICERAS COLORES", precio: 99, precioAnterior: 0, cat: "LIBRERÍA", foto: "fotos/LIBRERIA/5.webp", oferta: false, stock: true },
  { id: "LIB06", nombre: "SET MARCADORES DOBLE PUNTA X60", precio: 99, precioAnterior: 0, cat: "LIBRERÍA", foto: "fotos/LIBRERIA/6.webp", oferta: false, stock: true },

  // --- PROYECTORES ---
  { id: "PRO01", nombre: "PROYECTOR MINI", precio: 99, precioAnterior: 0, cat: "PROYECTORES", foto: "fotos/PROYECTORES/1.webp", oferta: false, stock: true },
  { id: "PRO02", nombre: "PROYECTOR 2", precio: 99, precioAnterior: 0, cat: "PROYECTORES", foto: "fotos/PROYECTORES/2.webp", oferta: false, stock: true },

  // --- RELOJES ---
  { id: "REL01", nombre: "RELOJ SMART", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/1.webp", oferta: false, stock: true },
  { id: "REL02", nombre: "RELOJ 2", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/2.webp", oferta: false, stock: true },
  { id: "REL03", nombre: "RELOJ 3", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/3.webp", oferta: false, stock: true },
  { id: "REL04", nombre: "RELOJ 4", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/4.webp", oferta: false, stock: true },
  { id: "REL05", nombre: "RELOJ 5", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/5.webp", oferta: false, stock: true },
  { id: "REL06", nombre: "RELOJ 6", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/6.webp", oferta: false, stock: true },
  { id: "REL07", nombre: "RELOJ 7", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/7.webp", oferta: false, stock: true },
  { id: "REL08", nombre: "RELOJ 8", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/8.webp", oferta: false, stock: true },
  { id: "REL09", nombre: "RELOJ 9", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/9.webp", oferta: false, stock: true },
  { id: "REL10", nombre: "RELOJ 10", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/10.webp", oferta: false, stock: true },
  { id: "REL11", nombre: "RELOJ 11", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/11.webp", oferta: false, stock: true },
  { id: "REL12", nombre: "RELOJ 12", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/12.webp", oferta: false, stock: true },
  { id: "REL13", nombre: "RELOJ 13", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/13.webp", oferta: false, stock: true },
  { id: "REL14", nombre: "RELOJ 14", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/14.webp", oferta: false, stock: true },
  { id: "REL15", nombre: "RELOJ 15", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/15.webp", oferta: false, stock: true },
  { id: "REL16", nombre: "RELOJ 16", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/16.webp", oferta: false, stock: true },
  { id: "REL17", nombre: "RELOJ 17", precio: 99, precioAnterior: 0, cat: "RELOJES", foto: "fotos/RELOJES/17.webp", oferta: false, stock: false },

  // --- CARGADORES ---
  { id: "CAR01", nombre: "CARGADOR 1", precio: 8500, precioAnterior: 11000, cat: "CARGADORES", foto: "fotos/CARGADORES/1.webp", oferta: true, stock: true },
  { id: "CAR02", nombre: "CARGADOR 2", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/2.webp", oferta: false, stock: true },
  { id: "CAR03", nombre: "CARGADOR 3", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/3.webp", oferta: false, stock: true },
  { id: "CAR04", nombre: "CARGADOR 4", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/4.webp", oferta: false, stock: true },
  { id: "CAR05", nombre: "CARGADOR 5", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/5.webp", oferta: false, stock: true },
  { id: "CAR06", nombre: "CARGADOR 6", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/6.webp", oferta: false, stock: true },
  { id: "CAR07", nombre: "CARGADOR 7", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/7.webp", oferta: false, stock: true },
  { id: "CAR08", nombre: "CARGADOR 8", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/8.webp", oferta: false, stock: true },
  { id: "CAR09", nombre: "CARGADOR 9", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/9.webp", oferta: false, stock: true },
  { id: "CAR10", nombre: "CARGADOR 10", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/10.webp", oferta: false, stock: true },
  { id: "CAR11", nombre: "CARGADOR 11", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/11.webp", oferta: false, stock: true },
  { id: "CAR12", nombre: "CARGADOR 12", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/12.webp", oferta: false, stock: true },
  { id: "CAR13", nombre: "CARGADOR 13", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/13.webp", oferta: false, stock: true },
  { id: "CAR14", nombre: "CARGADOR 14", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/14.webp", oferta: false, stock: true },
  { id: "CAR15", nombre: "CARGADOR 15", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/15.webp", oferta: false, stock: true },
  { id: "CAR16", nombre: "CARGADOR 16", precio: 99, precioAnterior: 0, cat: "CARGADORES", foto: "fotos/CARGADORES/16.webp", oferta: false, stock: true },

  // --- CELULARES ---
  { id: "CEL01", nombre: "NOKIA 106", precio: 48000, precioAnterior: 0, cat: "CELULARES", foto: "fotos/CELULARES/1.webp", oferta: false, stock: true },
  { id: "CEL02", nombre: "NOKIA 2660 FLIP", precio: 98000, precioAnterior: 0, cat: "CELULARES", foto: "fotos/CELULARES/2.webp", oferta: false, stock: true },
  { id: "CEL03", nombre: "LÍNEA IPHONE (Consultar modelos)", precio: "Consultar", precioAnterior: 0, cat: "CELULARES", foto: "fotos/CELULARES/3.webp", oferta: false, stock: true },
  { id: "CEL04", nombre: "LÍNEA SAMSUNG (Consultar modelos)", precio: "Consultar", precioAnterior: 0, cat: "CELULARES", foto: "fotos/CELULARES/4.webp", oferta: false, stock: true },
  { id: "CEL05", nombre: "LÍNEA XIAOMI (Consultar modelos)", precio: "Consultar", precioAnterior: 0, cat: "CELULARES", foto: "fotos/CELULARES/5.webp", oferta: false, stock: true },
  { id: "CEL06", nombre: "LÍNEA MOTOROLA (Consultar modelos)", precio: "Consultar", precioAnterior: 0, cat: "CELULARES", foto: "fotos/CELULARES/6.webp", oferta: false, stock: true },

  // --- DEPORTIVO ---
  { id: "DEP01", nombre: "RIÑONERA DEPORTIVA SLIM", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/1.webp", oferta: false, stock: true },
  { id: "DEP02", nombre: "RIÑONERA ELÁSTICA REFLECTANTE", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/2.webp", oferta: false, stock: true },
  { id: "DEP03", nombre: "PORTA CELULAR BRAZO", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/3.webp", oferta: false, stock: true },
  { id: "DEP04", nombre: "PORTA CELULAR BRAZO", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/4.webp", oferta: false, stock: true },
  { id: "DEP05", nombre: "LUZ LED SEGURIDAD BIBI", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/5.webp", oferta: false, stock: true },
  { id: "DEP06", nombre: "FUNDA CELULAR IMPERMEABLE", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/6.webp", oferta: false, stock: true },
  { id: "DEP07", nombre: "BOTELLA SET X 3", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/7.webp", oferta: false, stock: true },
  { id: "DEP08", nombre: "BOTELLA SPORT 800ML", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/8.webp", oferta: false, stock: true },
  { id: "DEP09", nombre: "BOTELLA 600 ML", precio: 99, precioAnterior: 0, cat: "DEPORTIVO", foto: "fotos/DEPORTIVO/9.webp", oferta: false, stock: true },

  // --- VARIOS ---
  { id: "VAR01", nombre: "ARO LED 26 CM", precio: 99, precioAnterior: 0, cat: "VARIOS", foto: "fotos/VARIOS/1.webp", oferta: false, stock: true },
  { id: "VAR02", nombre: "NAVAJA MULTIFUNCIÓN", precio: 99, precioAnterior: 0, cat: "VARIOS", foto: "fotos/VARIOS/8.webp", oferta: false, stock: true },
  { id: "VAR03", nombre: "AFILADOR CUCHILLOS PLEGABLE", precio: 99, precioAnterior: 0, cat: "VARIOS", foto: "fotos/VARIOS/9.webp", oferta: false, stock: true },
  { id: "VAR04", nombre: "CALCULADORA CIENTÍFICA", precio: 99, precioAnterior: 0, cat: "VARIOS", foto: "fotos/VARIOS/10.webp", oferta: false, stock: true },
  { id: "VAR05", nombre: "CALCULADORA ESCRITORIO", precio: 99, precioAnterior: 0, cat: "VARIOS", foto: "fotos/VARIOS/11.webp", oferta: false, stock: true },
  { id: "VAR06", nombre: "CALCULADORA 12", precio: 99, precioAnterior: 0, cat: "VARIOS", foto: "fotos/VARIOS/12.webp", oferta: false, stock: true },
  { id: "VAR07", nombre: "CALCULADORA 13", precio: 99, precioAnterior: 0, cat: "VARIOS", foto: "fotos/VARIOS/13.webp", oferta: false, stock: true },
];