const productos = [
  // --- BELLEZA ---
  { 
  id: 'BELL01', 
  nombre: 'SECADOR DE PELO PROFESIONAL ZAFIRE', 
  precio: 49000, 
  precioAnterior: 64999, 
  cat: 'BELLEZA', 
  foto: 'fotos/BELLEZA/3.webp', 
  oferta: true, 
  stock: true,
  descripcion: 'Potencia profesional de 2000W para un secado ultra rápido.\n\n• Motor AC de larga duración.\n• 2 velocidades y 2 niveles de calor.\n• Botón de aire frío para fijar el peinado.\n• Incluye 2 boquillas concentradoras.\n• Cable reforzado de 1,8 metros.'
},
  { id: 'BELL02', nombre: 'PLANCHITA DE PELO TITANIO PROFESIONAL', precio: 46000, precioAnterior: 54999, cat: 'BELLEZA', foto: 'fotos/BELLEZA/4.webp', oferta: true, stock: true },
  { id: 'BELL03', nombre: 'CEPILLO SECADOR ALISADOR', precio: 19999, precioAnterior: 0, cat: 'BELLEZA', foto: 'fotos/BELLEZA/cepillo.webp', oferta: false, stock: true },
  { id: 'BELL04', nombre: 'AFEITADORA ABS DORADA', precio: 5500, precioAnterior: 0, cat: 'BELLEZA', foto: 'fotos/BELLEZA/2.webp', oferta: false, stock: true },
  { id: 'BELL05', nombre: 'AFEITADORA ABS CROMO', precio: 6000, precioAnterior: 0, cat: 'BELLEZA', foto: 'fotos/BELLEZA/1.webp', oferta: false, stock: true },
  { id: 'BELL06', nombre: 'SECADOR DE PELO 1000W', precio: 24000, precioAnterior: 0, cat: 'BELLEZA', foto: 'fotos/BELLEZA/5.webp', oferta: false, stock: true },
  // --- HOGAR ---
  { id: 'HOG01', nombre: 'FREIDORA DE AIRE 1800W 10L', precio: 99999, precioAnterior: 168999, cat: 'HOGAR', foto: 'fotos/HOGAR/1.webp', oferta: true, stock: true },
  { id: 'HOG02', nombre: 'HORNO ELÉCTRICO 1500w 17l', precio: 79999, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/2.webp', oferta: false, stock: true },
  { id: 'HOG03', nombre: 'CAFETERA EXPRESSO 1000W 1.8L', precio: 142000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/3.webp', oferta: false, stock: true },
  { id: 'HOG04', nombre: 'DESCORCHADOR DE VINO', precio: 2000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/4.webp', oferta: false, stock: true },
  { id: 'HOG05', nombre: 'SET DESCORCHADOR 3 PIEZAS', precio: 9999, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/5.webp', oferta: false, stock: true },
  { id: 'HOG06', nombre: 'SET DESCORCHADOR 5 PIEZAS CON AJEDREZ', precio: 14500, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/6.webp', oferta: false, stock: true },
  { id: 'HOG07', nombre: 'SET DESCORCHADOR Y VERTEDOR', precio: 11000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/7.webp', oferta: false, stock: true },
  { id: 'HOG10', nombre: 'CAFETERA DE FILTRO 900W 650ML', precio: 26000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/10.webp', oferta: false, stock: true },
  { id: 'HOG11', nombre: 'CAFETERA DE FILTRO 1200W 1.25L', precio: 32000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/11.webp', oferta: false, stock: true },
  { id: 'HOG12', nombre: 'CAFETERA DE FILTRO 1500W 1.5L', precio: 38000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/12.webp', oferta: false, stock: true },
  { id: 'HOG13', nombre: 'CAFETERA PRENSA FRANCESA 350ML', precio: 13000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/13.webp', oferta: false, stock: true },
  { id: 'HOG14', nombre: 'BALANZA DE PRECISIÓN GRAMERA 0.1-500G', precio: 8000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/14.webp', oferta: false, stock: true },
  { id: 'HOG15', nombre: 'BALANZA DE COCINA BLANCA', precio: 9000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/20.webp', oferta: false, stock: true },
  { id: 'HOG16', nombre: 'BALANZA BAÑO DISEÑO FRUTAS 180KG', precio: 18000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/16.webp', oferta: false, stock: true },
  { id: 'HOG17', nombre: 'SANDWICHERA ANTIADHERENTE ORYX 750W', precio: 28000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/17.webp', oferta: false, stock: true },
  { id: 'HOG18', nombre: 'BALANZA COCINA ACERO INOX', precio: 10000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/18.webp', oferta: false, stock: true },
  { id: 'HOG19', nombre: 'MINI BALANZA GRAMERA PRECISION', precio: 7000, precioAnterior: 0, cat: 'HOGAR', foto: 'fotos/HOGAR/19.webp', oferta: false, stock: true },
  { id: 'HOG20', nombre: 'CEPILLO ELÉCTRICO DE LIMPIEZA MULTIUSO', precio: 35000, precioAnterior: 59000, cat: 'HOGAR', foto: 'fotos/HOGAR/21.webp', oferta: true, stock: true },

  // --- DECO ---
  { id: 'DEC01', nombre: 'LÁMPARA ATARDECER', precio: 10000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/1.webp', oferta: false, stock: true },
  { id: 'DEC02', nombre: 'HUMIDIFICADOR LLAMA', precio: 21000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/2.webp', oferta: false, stock: true },
  { id: 'DEC03', nombre: 'HUMIDIFICADOR HONGO', precio: 9000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/3.webp', oferta: false, stock: true },
  { id: 'DEC04', nombre: 'VELADOR GATITO FLEXIBLE', precio: 7000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/4.webp', oferta: false, stock: false },
  { id: 'DEC05', nombre: 'LÁMPARA ESCRITORIO ASTRONAUTA LUNA', precio: 7500, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/5.webp', oferta: false, stock: true },
  { id: 'DEC06', nombre: 'MINI LÁMPARA RGB CILINDRO', precio: 13000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/6.webp', oferta: false, stock: true },
  { id: 'DEC07', nombre: 'PROYECTOR ASTRONAUTA GALAXIA', precio: 16000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/7.webp', oferta: false, stock: true },
  { id: 'DEC08', nombre: 'LÁMPARA 3 EN 1', precio: 29999, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/8.webp', oferta: false, stock: true },
  { id: 'DEC09', nombre: 'HUMIDIFICADOR CON REJILLAS RGB', precio: 22000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/9.webp', oferta: false, stock: true },
  { id: 'DEC10', nombre: 'VELADOR LED ESCRITORIO PORTALÁPICES', precio: 11000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/10.webp', oferta: false, stock: true },
  { id: 'DEC11', nombre: 'VELADOR CANGREJO INFANTIL', precio: 8000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/11.webp', oferta: false, stock: true },
  { id: 'DEC12', nombre: 'VELADOR CARACOL INFANTIL', precio: 8000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/12.webp', oferta: false, stock: true },
  { id: 'DEC13', nombre: 'LÁMPARA DE PARED MODERNA ANTORCHA', precio: 15000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/13.webp', oferta: false, stock: true },
  { id: 'DEC14', nombre: 'VELADOR CAPIBARA', precio: 8000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/14.webp', oferta: false, stock: true },
  { id: 'DEC15', nombre: 'LÁMPARA ESCRITORIO INALÁMBRICA 2 EN 1', precio: 19000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/15.webp', oferta: false, stock: true },
  { id: 'DEC16', nombre: 'PROYECTOR ASTRONAUTA', precio: 23000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/16.webp', oferta: false, stock: true },
  { id: 'DEC17', nombre: 'PROYECTOR ESTRELLAS', precio: 10000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/17.webp', oferta: false, stock: true },
  { id: 'DEC18', nombre: 'VELADOR CARACOL', precio: 6000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/18.webp', oferta: false, stock: true },
  { id: 'DEC19', nombre: 'LÁMPARA CARGADOR LUNA', precio: 32000, precioAnterior: 58000, cat: 'DECO', foto: 'fotos/DECO/19.webp', oferta: true, stock: true },
  { id: 'DEC20', nombre: 'PROYECTOR ASTRONAUTA RGB', precio: 28000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/20.webp', oferta: true, stock: true },
  { id: 'DEC21', nombre: 'HUMIDIFICADOR RGB', precio: 22000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/21.webp', oferta: false, stock: true },
  { id: 'DEC22', nombre: 'LÁMPARA CLIP', precio: 12000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/22.webp', oferta: false, stock: true },
  { id: 'DEC23', nombre: 'LÁMPARA LED IMANTADA PORTÁTIL', precio: 15000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/23.webp', oferta: false, stock: true },
  { id: 'DEC24', nombre: 'LÁMPARA GALAXIA', precio: 20000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/24.webp', oferta: false, stock: true },
  { id: 'DEC25', nombre: 'LÁMPARA DE ESCRITORIO PORTALÁPICES', precio: 21000, precioAnterior: 0, cat: 'DECO', foto: 'fotos/DECO/25.webp', oferta: false, stock: true },
  // --- PARLANTES ---
  { id: 'PAR01', nombre: 'PARLANTE ASTRONAUTA KIDS BLUETOOTH LED', precio: 15000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/1.webp', oferta: false, stock: false },
  { id: 'PAR02', nombre: 'PARLANTE 6,5" 10W BLUETOOTH LED', precio: 28000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/2.webp', oferta: false, stock: true },
  { id: 'PAR03', nombre: 'PARLANTE 3" 5W BLUETOOTH', precio: 11000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/3.webp', oferta: false, stock: true },
  { id: 'PAR04', nombre: 'PARLANTE 6.5" 10W SPIDERMAN BLUETOOTH LED', precio: 24000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/4.webp', oferta: false, stock: true },
  { id: 'PAR05', nombre: 'PARLANTE 15" 30W BLUETOOTH LED', precio: 180000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/5.webp', oferta: false, stock: true },
  { id: 'PAR06', nombre: 'PARLANTE 3" 5W BLUETOOTH LED RGB', precio: 16000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/6.webp', oferta: false, stock: true },
  { id: 'PAR07', nombre: 'PARLANTE 3" 8W BLUETOOTH', precio: 11000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/7.webp', oferta: false, stock: true },
  { id: 'PAR08', nombre: 'PARLANTE 12" 15W BLUETOOTH', precio: 92000, precioAnterior: 119999, cat: 'PARLANTES', foto: 'fotos/PARLANTES/8.webp', oferta: true, stock: true },
  { id: 'PAR09', nombre: 'PARLANTE 3" 8W BLUETOOTH LED', precio: 22000, precioAnterior: 39999, cat: 'PARLANTES', foto: 'fotos/PARLANTES/9.webp', oferta: true, stock: true },
  { id: 'PAR10', nombre: 'PARLANTE 8" 15W BLUETOOTH LED', precio: 36000, precioAnterior: 59999, cat: 'PARLANTES', foto: 'fotos/PARLANTES/10.webp', oferta: true, stock: true },
  { id: 'PAR11', nombre: 'PARLANTE 6.5" 10W BLUETOOTH LED', precio: 24000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/11.webp', oferta: false, stock: true },
  { id: 'PAR12', nombre: 'PARLANTE 3W BLUETOOTH LED', precio: 11000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/12.webp', oferta: false, stock: true },
  { id: 'PAR13', nombre: 'PARLANTE 5W BLUETOOTH LED', precio: 16000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/13.webp', oferta: false, stock: true },
  { id: 'PAR14', nombre: 'PARLANTE 8" 15W BLUETOOTH LED', precio: 37000, precioAnterior: 64999, cat: 'PARLANTES', foto: 'fotos/PARLANTES/14.webp', oferta: true, stock: true },
  { id: 'PAR15', nombre: 'PARLANTE 3" 5W BLUETOOTH LED', precio: 15000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/15.webp', oferta: false, stock: true },
  { id: 'PAR16', nombre: 'PARLANTE 6,5" 800W (RMS) BLUETOOTH LED', precio: 29000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/16.webp', oferta: false, stock: true },
  { id: 'PAR17', nombre: 'PARLANTE DROP 3" 5W BLUETOOTH', precio: 9000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/17.webp', oferta: false, stock: true },
  { id: 'PAR18', nombre: 'PARLANTE SMALL 3" 5W', precio: 26000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/18.webp', oferta: false, stock: true },
  { id: 'PAR19', nombre: 'PARLANTE 3" 8W BLUETOOTH ', precio: 22000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/19.webp', oferta: false, stock: true },
  { id: 'PAR20', nombre: 'PARLANTE 2" LÁMPARA CARGADOR', precio: 21000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/20.webp', oferta: false, stock: true },
  { id: 'PAR21', nombre: 'PARLANTE 3" 5W BLUETOOTH LED', precio: 10000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/21.webp', oferta: false, stock: true },
  { id: 'PAR22', nombre: 'PARLANTE 3" 5W BLUETOOTH LED', precio: 10000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/22.webp', oferta: false, stock: true },
  { id: 'PAR23', nombre: 'PARLANTE GAMER CON MAG SAFE 3W', precio: 12000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/23.webp', oferta: false, stock: true },
  { id: 'PAR24', nombre: 'PARLANTE SMALL 6W ', precio: 12000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/24.webp', oferta: false, stock: true },
  { id: 'PAR25', nombre: 'PARLANTE 2" 3W BLUETOOTH LED ', precio: 10000, precioAnterior: 0, cat: 'PARLANTES', foto: 'fotos/PARLANTES/25.webp', oferta: false, stock: true },

  // --- MICROFONOS ---
  { id: 'MIC01', nombre: 'MICRÓFONO CORBATERO CLIP TIPO C', precio: 4000, precioAnterior: 0, cat: 'MICROFONOS', foto: 'fotos/MICROFONOS/1.webp', oferta: false, stock: true },
  { id: 'MIC02', nombre: 'MICRÓFONO DOBLE INALÁMBRICO PROFESIONAL', precio: 50000, precioAnterior: 64999, cat: 'MICROFONOS', foto: 'fotos/MICROFONOS/2.webp', oferta: true, stock: true },
  { id: 'MIC03', nombre: 'MICRÓFONO CLIP INALÁMBRICO TIPO C', precio: 16000, precioAnterior: 0, cat: 'MICROFONOS', foto: 'fotos/MICROFONOS/3.webp', oferta: false, stock: true, desc:"MICRÓFONO CLIP INALÁMBRICO TIPO C"},
  { id: 'MIC04', nombre: 'MICRÓFONO INALÁMBRICO CON ESTUCHE DE CARGA', precio: 30000, precioAnterior: 48900, cat: 'MICROFONOS', foto: 'fotos/MICROFONOS/4.webp', oferta: true, stock: true },
  { id: 'MIC05', nombre: 'MICRÓFONO MICRÓFONO CORBATERO CLIP TIPO C + LIGHTNING', precio: 13000, precioAnterior: 0, cat: 'MICROFONOS', foto: 'fotos/MICROFONOS/5.webp', oferta: false, stock: true },
  { id: 'MIC06', nombre: 'MICRÓFONO GAMER RGB', precio: 32000, precioAnterior: 45999, cat: 'MICROFONOS', foto: 'fotos/MICROFONOS/6.webp', oferta: true, stock: true },
  { id: 'MIC07', nombre: 'MICRÓFONO CON PARLANTE RECARGABLE', precio: 12000, precioAnterior: 0, cat: 'MICROFONOS', foto: 'fotos/MICROFONOS/7.webp', oferta: false, stock: true },

  // --- AURICULARES ---
  { id: 'AUR01', nombre: 'AURICULAR BLUETOOTH SWEET', precio: 8000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/1.webp', oferta: false, stock: true },
  { id: 'AUR02', nombre: 'AURICULAR VINCHA CABLE 1,2M ', precio: 7000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/2.webp', oferta: false, stock: true },
  { id: 'AUR03', nombre: 'AURICULAR BLUETOOTH ZENIX', precio: 14000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/3.webp', oferta: false, stock: false },
  { id: 'AUR04', nombre: 'AURICULAR KIDS CON CABLE ', precio: 10000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/4.webp', oferta: false, stock: true },
  { id: 'AUR05', nombre: 'AURICULAR PLUS ACTIVE CON CABLE', precio: 12000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/5.webp', oferta: false, stock: true },
  { id: 'AUR06', nombre: 'AURICULAR GLOW CON CABLE 1,2M', precio: 11000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/6.webp', oferta: false, stock: true },
  { id: 'AUR07', nombre: 'AURICULAR RADIANCE BLUETOOTH + CABLE 1,2M', precio: 50000, precioAnterior: 65000, cat: 'AURICULARES', foto: 'fotos/AURICULARES/7.webp', oferta: true, stock: true },
  { id: 'AUR08', nombre: 'AURICULARES ROMPEOIDOS CABLE', precio: 2000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/8.webp', oferta: false, stock: true },
  { id: 'AUR09', nombre: 'AURICULARES KIDS', precio: 3000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/9.webp', oferta: false, stock: true },
  { id: 'AUR10', nombre: 'AURICULARES ROMPEOIDOS 4', precio: 2000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/10.webp', oferta: false, stock: true },
  { id: 'AUR11', nombre: 'AURICULARES MANOS LIBRES TWS', precio: 12000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/11.webp', oferta: false, stock: true },
  { id: 'AUR12', nombre: 'AURICULARES MANOS LIBRES TWS RUNBEAT', precio: 26000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/12.webp', oferta: false, stock: true },
  { id: 'AUR13', nombre: 'AURICULARES MANOS LIBRES TWS', precio: 12000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/13.webp', oferta: false, stock: true },
  { id: 'AUR14', nombre: 'AURICULARES ', precio: 0, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/14.webp', oferta: false, stock: false },
  { id: 'AUR15', nombre: 'AURICULARES TMW NOX PANTALLA TOUCH', precio: 35000, precioAnterior: 49999, cat: 'AURICULARES', foto: 'fotos/AURICULARES/15.webp', oferta: true, stock: true },
  { id: 'AUR16', nombre: 'AURICULARES BLUETOOTH INALÁMBRICO SPORT', precio: 10000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/16.webp', oferta: false, stock: true },
  { id: 'AUR17', nombre: 'AURICULARES MANOS LIBRES TWS', precio: 14000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/17.webp', oferta: false, stock: true },
  { id: 'AUR18', nombre: 'AURICULARES LETS', precio: 1500, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/18.webp', oferta: false, stock: true },
  { id: 'AUR19', nombre: 'AURICULARES BLUETOOTH OREJAS GATITO', precio: 10000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/19.webp', oferta: false, stock: true },
  { id: 'AUR21', nombre: 'AURICULARES BLUETOOTH + CABLE', precio: 24000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/20.webp', oferta: false, stock: true },
  { id: 'AUR22', nombre: 'AURICULARES KIDS BLUETOOTH + CABLE', precio: 9000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/21.webp', oferta: false, stock: true },
{ id: 'AUR23', nombre: 'AURICULARES CON CABLE NOISE', precio: 12000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/22.webp', oferta: false, stock: true },
{ id: 'AUR24', nombre: 'AURICULARES BLUETOOTH + CABLE', precio: 15000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/23.webp', oferta: false, stock: true },
{ id: 'AUR25', nombre: 'AURICULARES BOOM BLUETOOTH + CABLE', precio: 20000, precioAnterior: 0, cat: 'AURICULARES', foto: 'fotos/AURICULARES/24.webp', oferta: false, stock: true },

  // --- INFORMÁTICA ---
  { id: 'INF01', nombre: 'TV BOX 4K ANDROID 14 4-32GB', precio: 66000, precioAnterior: 78000, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/1.webp', oferta: true, stock: true },
  { id: 'INF02', nombre: 'TV BOX 4K ANDROID 14 2-16GB', precio: 60000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/2.webp', oferta: false, stock: true },
  { id: 'INF03', nombre: 'MOUSE GAMER CON CABLE RGB', precio: 15000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/3.webp', oferta: false, stock: true },
  { id: 'INF04', nombre: 'MOUSE CON CABLE', precio: 4000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/4.webp', oferta: false, stock: true },
  { id: 'INF05', nombre: 'MOUSE PAD', precio: 4000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/5.webp', oferta: false, stock: true },
  { id: 'INF06', nombre: 'COMBO INALÁMBRICO RECARGABLE', precio: 45000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/6.webp', oferta: false, stock: true },
  { id: 'INF07', nombre: 'COMBO TECLADO Y MOUSE GAMER RGB', precio: 25000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/7.webp', oferta: false, stock: true },
  { id: 'INF08', nombre: 'JOYSTICK PC/PS3/TV A PILAS', precio: 20000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/8.webp', oferta: false, stock: true },
  { id: 'INF09', nombre: 'COMBO TECLADO + MOUSE INALÁMBRICO', precio: 20000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/9.webp', oferta: false, stock: true },
  { id: 'INF14', nombre: 'MOUSE CON CABLE', precio: 5000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/14.webp', oferta: false, stock: true },
  { id: 'INF15', nombre: 'MOUSE INALÁMBRICO', precio: 8000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/INFORMATICA/15.webp', oferta: false, stock: true },
  { id: 'INF16', nombre: 'CARGADOR UNIVERSAL PARA NOTEBOOK 8 PINES 90W', precio: 32000, precioAnterior: 0, cat: 'INFORMÁTICA', foto: 'fotos/CARGADORES/14.webp', oferta: false, stock: true },
  // --- JUGUETES ---
  { id: 'JUG01', nombre: 'CÁMARA DIGITAL INFANTIL', precio: 11000, precioAnterior: 0, cat: 'JUGUETES', foto: 'fotos/JUGUETES/1.webp', oferta: false, stock: true },
  { id: 'JUG02', nombre: 'CAMIÓN DE CONSTRUCCIÓN BLOQUES', precio: 14000, precioAnterior: 0, cat: 'JUGUETES', foto: 'fotos/JUGUETES/2.webp', oferta: false, stock: true },
  { id: 'JUG03', nombre: 'COMBO PISTOLA LANZA DARDOS + MUNICIÓN', precio: 30000, precioAnterior: 0, cat: 'JUGUETES', foto: 'fotos/JUGUETES/3.webp', oferta: false, stock: true },
  { id: 'JUG04', nombre: 'AMETRALLADORA AUTOMÁTICA DORADA', precio: 34000, precioAnterior: 78900, cat: 'JUGUETES', foto: 'fotos/JUGUETES/4.webp', oferta: true, stock: true },
  { id: 'JUG05', nombre: 'SET LANZA DARDOS + ACCESORIOS', precio: 19000, precioAnterior: 0, cat: 'JUGUETES', foto: 'fotos/JUGUETES/5.webp', oferta: false, stock: true },
  { id: 'JUG06', nombre: 'PISTOLA AUTOMÁTICA', precio: 28000, precioAnterior: 42000, cat: 'JUGUETES', foto: 'fotos/JUGUETES/6.webp', oferta: true, stock: true },

  // --- LIBRERÍA ---
  { id: 'LIB01', nombre: 'SET RESALTADORES FRAGANCIA', precio: 4500, precioAnterior: 0, cat: 'LIBRERIA', foto: 'fotos/LIBRERIA/1.webp', oferta: false, stock: true },
  { id: 'LIB02', nombre: 'MOCHILA INFANTIL DINO', precio: 18000, precioAnterior: 0, cat: 'LIBRERIA', foto: 'fotos/LIBRERIA/2.webp', oferta: false, stock: true },
  { id: 'LIB03', nombre: 'MOCHILA INFANTIL LECHUZA', precio: 12000, precioAnterior: 0, cat: 'LIBRERIA', foto: 'fotos/LIBRERIA/3.webp', oferta: false, stock: true },
  { id: 'LIB04', nombre: 'MOCHILA ESCOLAR ESPACIAL', precio: 28000, precioAnterior: 42000, cat: 'LIBRERIA', foto: 'fotos/LIBRERIA/4.webp', oferta: true, stock: true },
  { id: 'LIB05', nombre: 'SET LAPICERAS COLORES X48', precio: 23000, precioAnterior: 0, cat: 'LIBRERIA', foto: 'fotos/LIBRERIA/5.webp', oferta: false, stock: true },
  { id: 'LIB06', nombre: 'SET MARCADORES DOBLE PUNTA X60', precio: 18000, precioAnterior: 0, cat: 'LIBRERIA', foto: 'fotos/LIBRERIA/6.webp', oferta: false, stock: true },
  
  //---ACCESORIOS CELULARES---
 
  { id: 'ACC01', nombre: 'SOPORTE SELFIE SOPAPA', precio: 1500, precioAnterior: 0, cat: 'ACCESORIOS_CELULARES', foto: 'fotos/ACCESORIOSCELULARES/1.webp', oferta: false, stock: true },
  { id: 'ACC02', nombre: 'SOPORTE UNIVERSAL PARA DISPOSITIVOS MÓVILES', precio: 4000, precioAnterior: 0, cat: 'ACCESORIOS_CELULARES', foto: 'fotos/ACCESORIOSCELULARES/2.webp', oferta: false, stock: true },
  { id: 'ACC03', nombre: 'HOLDER MAGNÉTICO FIJO', precio: 3000, precioAnterior: 0, cat: 'ACCESORIOS_CELULARES', foto: 'fotos/ACCESORIOSCELULARES/3.webp', oferta: false, stock: true },
  { id: 'ACC04', nombre: 'HOLDER FREE STYLE 360°', precio: 3000, precioAnterior: 0, cat: 'ACCESORIOS_CELULARES', foto: 'fotos/ACCESORIOSCELULARES/4.webp', oferta: false, stock: true },
  { id: 'ACC05', nombre: 'HOLDER CARGADOR INALÁMBRICO 15W PARA AUTO', precio: 15000, precioAnterior: 0, cat: 'ACCESORIOS_CELULARES', foto: 'fotos/ACCESORIOSCELULARES/5.webp', oferta: false, stock: true },
  { id: 'ACC06', nombre: 'CORREA PARA CELULAR SAFE BAND', precio: 8000, precioAnterior: 0, cat: 'ACCESORIOS_CELULARES', foto: 'fotos/ACCESORIOSCELULARES/6.webp', oferta: false, stock: true },
  { id: 'ACC07', nombre: 'HOLDER CARGADOR INALÁMBRICO 15W', precio: 32000, precioAnterior: 0, cat: 'ACCESORIOS_CELULARES', foto: 'fotos/ACCESORIOSCELULARES/7.webp', oferta: false, stock: true },

  // --- PROYECTORES ---
  { id: 'PRO01', nombre: 'PROYECTOR PIXORA', precio: 150000, precioAnterior: 269999, cat: 'PROYECTORES', foto: 'fotos/PROYECTORES/1.webp', oferta: true, stock: true },
  { id: 'PRO02', nombre: 'PROYECTOR ORVA', precio:100000, precioAnterior: 0, cat: 'PROYECTORES', foto: 'fotos/PROYECTORES/2.webp', oferta: false, stock: true },

  //---CABLES---
  { id: 'CAB01', nombre: 'ADAPTADOR HDMI A 2 HDMI', precio: 5000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/1.webp', oferta: false, stock: true },
  { id: 'CAB02', nombre: 'CABLE USB a C', precio: 2000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/2.webp', oferta: false, stock: true },
  { id: 'CAB03', nombre: 'CABLE USB a V8', precio: 2000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/3.webp', oferta: false, stock: true },
  { id: 'CAB04', nombre: 'CABLE USB a C', precio: 2500, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/4.webp', oferta: false, stock: true },
  { id: 'CAB05', nombre: 'CABLE USB a C', precio: 2500, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/5.webp', oferta: false, stock: true },
  { id: 'CAB06', nombre: 'CABLE AUX 3,5-2M', precio: 3000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/6.webp', oferta: false, stock: true },
  { id: 'CAB07', nombre: 'CABLE AUX 3,5-1.8M ESPIRAL', precio: 3000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/7.webp', oferta: false, stock: true },
  { id: 'CAB08', nombre: 'CABLE HDMI GOMA 3M', precio: 4000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/8.webp', oferta: false, stock: true },
  { id: 'CAB09', nombre: 'CABLE C a C', precio: 5000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/9.webp', oferta: false, stock: true },
  { id: 'CAB10', nombre: 'CABLE HDMI a VGA 1.5M', precio: 5000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/10.webp', oferta: false, stock: true },
  { id: 'CAB11', nombre: 'CABLE C A LIGHTNING', precio: 6000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/11.webp', oferta: false, stock: true },
  { id: 'CAB12', nombre: 'CABLE 2 PUNTAS LIGHTNING y V8 ', precio: 8000, precioAnterior: 0, cat: 'CABLES', foto: 'fotos/CABLES/12.webp', oferta: false, stock: true },


  // --- RELOJES ---
  { id: 'REL01', nombre: 'RELOJ KIDS', precio: 3500, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/1.webp', oferta: false, stock: true },
  { id: 'REL02', nombre: 'SMART WATCH D20', precio: 8000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/2.webp', oferta: false, stock: true },
  { id: 'REL03', nombre: 'SMART WATCH T500', precio: 12000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/3.webp', oferta: false, stock: true },
  { id: 'REL04', nombre: 'SMART WATCH I8 PRO MAX', precio: 16000, precioAnterior: 32000, cat: 'RELOJES', foto: 'fotos/RELOJES/4.webp', oferta: true, stock: true },
  { id: 'REL05', nombre: 'RELOJ FEMENINO KL', precio: 8000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/5.webp', oferta: false, stock: true },
  { id: 'REL08', nombre: 'SMART WATCH I7', precio: 11000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/6.webp', oferta: false, stock: true },
  { id: 'REL07', nombre: 'SMART BAND M8', precio: 8000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/7.webp', oferta: true, stock: true },
  { id: 'REL06', nombre: 'RELOJ DE MESA DIGITAL', precio: 11000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/8.webp', oferta: false, stock: false },
  { id: 'REL09', nombre: 'SMART WATCH SU-80', precio: 23000, precioAnterior: 38000, cat: 'RELOJES', foto: 'fotos/RELOJES/9.webp', oferta: true, stock: true },
  { id: 'REL10', nombre: 'SMART WATCH 4 PRO', precio:28000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/10.webp', oferta: false, stock: true },
  { id: 'REL11', nombre: 'SMART WATCH GT4', precio: 30000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/11.webp', oferta: false, stock: true },
  { id: 'REL12', nombre: 'RELOJ LX01', precio: 4000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/12.webp', oferta: false, stock: true },
  { id: 'REL13', nombre: 'WATCH BAND KIDS', precio: 2000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/13.webp', oferta: false, stock: true },
  { id: 'REL14', nombre: 'RELOJ GENOVA Z166 LIGTH', precio: 4000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/14.webp', oferta: false, stock: true },
  { id: 'REL15', nombre: 'RELOJ MASCULINO S612', precio: 6000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/15.webp', oferta: false, stock: true },
  { id: 'REL16', nombre: 'RELOJ FEMENINO 8061', precio: 8000, precioAnterior: 0, cat: 'RELOJES', foto: 'fotos/RELOJES/16.webp', oferta: false, stock: true },
  { id: 'REL17', nombre: 'SMART WATCH A58 + JOYERIA', precio: 34000, precioAnterior: 48000, cat: 'RELOJES', foto: 'fotos/RELOJES/17.webp', oferta: true, stock: true },

  // --- CARGADORES---
  { id: 'CAR01', nombre: 'CARGADOR PARA AUTO 12V POWERED V8 ', precio: 5000, precioAnterior: 11000, cat: 'CARGADORES', foto: 'fotos/CARGADORES/1.webp', oferta:false, stock: true },
  { id: 'CAR03', nombre: 'CARGADOR WIRELESS ION / MAGSAFE 15W', precio: 7000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/3.webp', oferta: false, stock: true },
  { id: 'CAR04', nombre: 'CARGADOR CARGA RÁPIDA 45W TIPO C + PD', precio: 8000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/4.webp', oferta: false, stock: true },
  { id: 'CAR05', nombre: 'CARGADOR USB CON CABLE V8', precio: 3000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/5.webp', oferta: false, stock: true },
  { id: 'CAR07', nombre: 'LÁMPARA INALÁMBRICA + CARGA RÁPIDA 15W', precio: 16000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/7.webp', oferta: false, stock: true },
  { id: 'CAR08', nombre: 'CARGADOR CARGA RÁPIDA 55W 1 USB + 1TIPO C', precio: 18000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/8.webp', oferta: false, stock: true },
  { id: 'CAR10', nombre: 'CARGADOR WIRELESS 3 EN 1 PARA APPLE 25W', precio: 18000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/10.webp', oferta: false, stock: true },
  { id: 'CAR13', nombre: 'ESTACIÓN DE CARGA INALÁMBRICA 3 EN 1 15W', precio: 32000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/13.webp', oferta: false, stock: true },
  { id: 'VAR14', nombre: 'CARGADOR CARGA RÁPIDA 65W 1 USB + 2TIPO C ', precio: 21000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/11.webp', oferta: false, stock: true },
  { id: 'CAR15', nombre: 'ESTACIÓN DE CARGA INALÁMBRICA 4 EN 1 15W', precio: 40000, precioAnterior: 56000, cat: 'CARGADORES', foto: 'fotos/CARGADORES/15.webp', oferta: true, stock: true },
  { id: 'CAR16', nombre: 'CARGADOR DE AUTO V8', precio: 4000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/16.webp', oferta: false, stock: true },
  { id: 'CAR16', nombre: 'CARGADOR WIRELESS 20W', precio: 9000, precioAnterior: 0, cat: 'CARGADORES', foto: 'fotos/CARGADORES/17.webp', oferta: false, stock: true },

  // --- CELULARES ---
  { id: 'CEL01', nombre: 'NOKIA 106', precio: 48000, precioAnterior: 0, cat: 'CELULARES', foto: 'fotos/CELULARES/1.webp', oferta: false, stock: true },
  { id: 'CEL02', nombre: 'NOKIA 2660 FLIP', precio: 98000, precioAnterior: 0, cat: 'CELULARES', foto: 'fotos/CELULARES/2.webp', oferta: false, stock: true },
  { id: 'CEL03', nombre: 'LÍNEA IPHONE (Todos los modelos)', precio: 'Consultar', precioAnterior: 0, cat: 'CELULARES', foto: 'fotos/CELULARES/3.webp', oferta: false, stock: true },
  { id: 'CEL04', nombre: 'LÍNEA SAMSUNG (Todos los modelos)', precio: 'Consultar', precioAnterior: 0, cat: 'CELULARES', foto: 'fotos/CELULARES/4.webp', oferta: false, stock: true },
  { id: 'CEL05', nombre: 'LÍNEA XIAOMI (Todos los modelos)', precio: 'Consultar', precioAnterior: 0, cat: 'CELULARES', foto: 'fotos/CELULARES/5.webp', oferta: false, stock: true },
  { id: 'CEL06', nombre: 'LÍNEA MOTOROLA (Todos los modelos)', precio: 'Consultar', precioAnterior: 0, cat: 'CELULARES', foto: 'fotos/CELULARES/6.webp', oferta: false, stock: true },

  // --- DEPORTIVO ---
  { id: 'DEP01', nombre: 'RIÑONERA + PORTABOTELLA', precio: 6000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/1.webp', oferta: false, stock: true },
  { id: 'DEP02', nombre: 'RIÑONERA ELÁSTICA', precio: 5000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/2.webp', oferta: false, stock: true },
  { id: 'DEP03', nombre: 'BRAZALLETE PORTA CELULAR', precio: 2000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/3.webp', oferta: false, stock: true },
  { id: 'DEP04', nombre: 'BRAZALLETE PORTA CELULAR', precio: 4000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/4.webp', oferta: false, stock: true },
  { id: 'DEP10', nombre: 'BRAZALLETE PORTA CELULAR 2 ESPACIOS CIERRES', precio: 5000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/10.webp', oferta: false, stock: true },
  { id: 'DEP05', nombre: 'LUZ LED SEGURIDAD BICI', precio: 9000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/5.webp', oferta: false, stock: true },
  { id: 'DEP07', nombre: 'BOTELLA SET X 3 2000ML 900ML 300ML', precio: 13000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/7.webp', oferta: false, stock: true },
  { id: 'DEP08', nombre: 'BOTELLA SPORT 800ML', precio: 9000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/8.webp', oferta: false, stock: true },
  { id: 'DEP09', nombre: 'BOTELLA 600 ML', precio: 10000, precioAnterior: 0, cat: 'DEPORTIVO', foto: 'fotos/DEPORTIVO/9.webp', oferta: false, stock: true },
  // --- VARIOS ---
  { id: 'VAR01', nombre: 'ARO LED 26 CM 3 TONOS DE LUZ 12W', precio: 8000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/1.webp', oferta: false, stock: true },
  { id: 'VAR02', nombre: 'NAVAJA MULTIFUNCIÓN', precio: 6000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/8.webp', oferta: false, stock: true },
  { id: 'VAR03', nombre: 'AFILADOR CUCHILLOS PLEGABLE', precio: 8000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/9.webp', oferta: false, stock: true },
  { id: 'VAR04', nombre: 'CALCULADORA GRANDE', precio: 11000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/10.webp', oferta: false, stock: true },
  { id: 'VAR05', nombre: 'CALCULADORA CLÁSICA GRANDE', precio: 6000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/11.webp', oferta: false, stock: true },
  { id: 'VAR06', nombre: 'CALCULADORA DE BOLSILLO CON TAPA', precio: 4000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/12.webp', oferta: false, stock: true },
  { id: 'VAR07', nombre: 'CALCULADORA CHICA', precio: 8000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/13.webp', oferta: false, stock: true },
  { id: 'VAR08', nombre: 'CORREA CROSSBODY', precio: 4000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/DEPORTIVO/6.webp', oferta: false, stock: true },
  { id: 'VAR09', nombre: 'KIT FUNDA Y COMECABLE PARA CARGADOR', precio: 9000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/4.webp', oferta: false, stock: true },
  { id: 'VAR10', nombre: 'BOTELLA INFANTIL 640ML', precio: 11000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/2.webp', oferta: false, stock: true },
  { id: 'VAR11', nombre: 'ORGANIZADOR DE CABLES CHICO', precio: 5000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/5.webp', oferta: false, stock: true },
  { id: 'VAR12', nombre: 'ORGANIZADOR DE CABLES GRANDE', precio: 6000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/3.webp', oferta: false, stock: true },
  { id: 'VAR13', nombre: 'CARGADOR DE PILAS CUÁDRUPLE TIPO C', precio: 14000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/CARGADORES/6.webp', oferta: false, stock: true },
  { id: 'VAR15', nombre: 'CARGADOR PARA 4 PILAS CON USB', precio: 21000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/CARGADORES/12.webp', oferta: false, stock: true },
  { id: 'VAR16', nombre: 'CARGADOR DE PILAS DOBLE USB-C', precio: 6000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/CARGADORES/2.webp', oferta: false, stock: true },
  { id: 'VAR17', nombre: 'CARGADOR DE PILAS DOBLE', precio: 16000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/CARGADORES/9.webp', oferta: false, stock: true },
  { id: 'VAR18', nombre: 'INFLADOR AUTOMÁTICO PORTÁTIL', precio: 38000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/14.webp', oferta: false, stock: true },
  { id: 'VAR19', nombre: 'ADAPTADOR UNIVERSAL GLOBALINK', precio: 5000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/15.webp', oferta: false, stock: true },
  { id: 'VAR20', nombre: 'ADAPTADOR MICROSD A USB', precio: 3000, precioAnterior: 0, cat: 'VARIOS', foto: 'fotos/VARIOS/16.webp', oferta: false, stock: true },


];